name: "CI Multiplatform Build"

# This is an example of a CI workflow that builds the project on all desktop platforms

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: "CI Multiplatform Build"
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-15-intel, macos-latest, ubuntu-latest, ubuntu-24.04-arm]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

#    - name: Setup interactive tmate session
#      uses: mxschmitt/action-tmate@v3

    - name: apt install xorg-dev  libglfw3-dev (ubuntu only)
      if: ${{ matrix.platform == 'ubuntu-latest' || matrix.platform == 'ubuntu-24.04-arm' }}
      run: sudo apt-get update && sudo apt-get install -y xorg-dev  libglfw3-dev

    - name: Build on ${{ matrix.platform }}
      run: |
        cmake -S . -B build -DHELLOIMGUI_DOWNLOAD_FREETYPE_IF_NEEDED=ON -DCMAKE_BUILD_TYPE=Release
        cmake --build build --config Release


  build-emscripten:
    name: "Build Emscripten"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install emscripten
      run: ./third_party/hello_imgui/tools/emscripten/install_emscripten.sh

    - name: Build with emscripten
      run: |
        source ~/emsdk/emsdk_env.sh
        emcmake cmake -S . -B build-emscripten -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_C_FLAGS="-pthread -sUSE_GLFW=3" \
          -DCMAKE_CXX_FLAGS="-pthread -sUSE_GLFW=3" \
          -DCMAKE_EXE_LINKER_FLAGS="-pthread -sFULL_ES3=1 -sUSE_GLFW=3 -sPROXY_TO_PTHREAD -sPTHREAD_POOL_SIZE=2 -sUSE_WEBGL2=1 -sMIN_WEBGL_VERSION=1 -sMAX_WEBGL_VERSION=2"
        cmake --build build-emscripten

    - name: Stage emscripten build
      run: |
        mkdir -p shoecomp-emscripten
        cp build-emscripten/shoecomp.html shoecomp-emscripten/
        cp build-emscripten/shoecomp.js shoecomp-emscripten/
        cp build-emscripten/shoecomp.wasm shoecomp-emscripten/
        for f in build-emscripten/shoecomp.data build-emscripten/shoecomp.worker.js; do
          [ -f "$f" ] && cp "$f" shoecomp-emscripten/
        done
        zip -r shoecomp-emscripten.zip shoecomp-emscripten/
